In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

# Loading all necessary libraries


In [32]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/scikit-learn-videos/master/data/Advertising.csv")
#Loading Data

In [7]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [9]:
pf=ProfileReport(df)
#Generating Reports

In [10]:
pf.to_widgets()
#Generating it in a beautifull manner

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
pf.to_file("reporting.html")
#Saving Reports as html file

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
x=df[['TV']]

In [16]:
y=df.Sales

In [17]:
from sklearn.linear_model import LinearRegression

In [21]:
linear=LinearRegression()

In [22]:
linear.fit(x,y)

LinearRegression()

In [ ]:
# Y=m.X+c

In [23]:
linear.intercept_
#Values of c 

7.032593549127693

In [24]:
linear.coef_
#Value of m

array([0.04753664])

In [25]:
linear.predict([[450]])

array([28.42408174])

In [26]:
file="LinearRegression.sav"
#.sav is file format

In [27]:
pickle.dump(linear,open(file,'wb'))
#saving that model

In [28]:
saved_model=pickle.load(open(file,'rb'))

In [30]:
saved_model.predict([[45]])

array([9.17174237])